<a href="https://colab.research.google.com/github/HKyeol/Python_study/blob/master/201222CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 150. 이미지를 숫자로 변환하는 방법 ( 폐사진 )

딥러닝 수업을 할 때 이미지를 인공 신경망에 넣어서 학습을 시키는데 인공 신경망에 사진을 넣을 때 숫자로 변환을 해서 넣어야 합니다.  

c 드라이브 밑에 images 라는 폴더에 폐사진 20장을 가져다 두세요~  
```
사진 ------------------> 인공 신경망 ------------------> 폐결절
                               정상폐
                                 폐암 
                                   :
                              7~10가지 분류 판정
```
공항 검색대에 입국할 때 위반되는 물건을 반입하려고 하면 못하게 막기위해 사람이 모니터링을 하는데 … 딥러닝 기술으로 컴퓨터가 알아내도록 하려는 기술을 구현  

c 드라이브 밑에 images 라는 폴더에 폐사진 20장이 있어야 합니다.  

예제1. c 드라이브 밑에 images 폴더에 있는 사진들의 이름을 불러오는 함수를 행성합니다.

In [ ]:
import os
test_image = 'c:\\images'

def image_load(path):
    file_list = os.listdir(path) # 해당 디렉토리의 파일명을 추출한다.
    return file_list
print(image_load(test_image))

예제2. 위의 결과에서 숫자만 나오게 함수의 코드를 수정하시오.

In [ ]:
import os
import re # 데이터 정제전문 모듈
test_image = 'c:\\images'
file_name = []
def image_load(path):
    file_list = os.listdir(path) # 해당 디렉토리의 파일명을 추출한다.
    for i in file_list:
        a= re.sub('[^0-9]','',i) # i의 값 중에서 숫자가 아닌 것들은 싱글 두개를 붙인('') null로 변경해라
        file_name.append(a)      # ^ 꺾쇠는 ~ not을 의미함 아니면 '' 맞으면 i
    return file_name
print(image_load(test_image))

문제476. 위에서 출력되는 리스트 안의 요소들은 문자입니다. 그런데 문자가 아니라 숫자로 되게 하시오

In [ ]:
file_name.append(int(a)) # 를 넣어줌

문제477. 위의 리스트의 요소가 ascending하게 정렬되게 하시오.

In [ ]:
file_name.append(int(a))
file_name.sort() # 를 붙여줌

문제478. 위의 함수의 코드를 추가해서 아래와 같이 출력되게 하시오.
```
['1.png', '2.png', ... ]
```

In [ ]:
import os
import re # 데이터 정제전문 모듈
test_image = 'c:\\images'
file_name = []
def image_load(path):
    file_list = os.listdir(path) # 해당 디렉토리의 파일명을 추출한다.
    for i in file_list:
        a= re.sub('[^0-9]','',i)
        file_name.append(int(a))
    file_name.sort()
    file_res=[]
    for k in file_name:
        file_res.append(str(k)+'.png')
    return file_res
print(image_load(test_image))


인공신경망에 넣으려면 경로를 다 써줘야한다.  

문제479. 위의 함수의 코드를 수정해서 아래와 같이 이름 앞에 절대경로가 붙게 하시오.
```
['c:\\images\\1.png, ... ]
```


In [ ]:
    for k in file_name:
        file_res.append(test_image+'\\'+str(k)+'.png')  # 바꿔준다.
    return file_res

인공신경망에 넣으려면 숫자로 변환해야 한다.  

예제3. 폐사진 이미지를 숫자로 변환하기 위하여 필요한 파이썬 모듈을 install 하시오.  

아나콘다 프롬프트 창을 엽니다.
```
conda install opencv
```
위의 명령어가 에러가 나면 아래와 같이 하시오.
```
pip install opencv-python
```
설명: opencv 모듈은 이미지를 파이썬에서 숫자로 변환하고 다양한 이미지처리를 할 수 있게 해주는 기술을 제공해주는 함수  

예: 구글지도나 카카오 지도, 네이버 지도에 보면 street view가 있는데 거기에 사람얼굴이나 자동차 번호판을 모자이크 처리를 해줘야 합니다.  

예제4. 위에서 설치한 opencv 모듈을 이용해서 폐사진을 숫자로 변환한다.

In [5]:
import cv2 # opencv 모듈을 임포트 하겠다.

In [ ]:
import cv2 # opencv 모듈을 임포트 하겠다.
import os
import re # 데이터 정제전문 모듈
test_image = 'c:\\images'
file_name = []
def image_load(path):
    file_list = os.listdir(path) # 해당 디렉토리의 파일명을 추출한다.
    for i in file_list:
        a= re.sub('[^0-9]','',i)
        file_name.append(int(a))
    file_name.sort()
    file_res=[]
    for k in file_name:
        file_res.append(test_image+'\\'+str(k)+'.png')
    image = []
    for h in file_res:
        img = cv2.imread(h)
        image.append(img)
    return image
print(image_load(test_image))

예제5. 위의 숫자로 변환한 리스트를 인공 신경망에 넣기 위해서는 numpy 모듈의 array 형태로 제공을 해줘야 합니다. 위의 리스트를 numpy array로 변환합니다.

In [ ]:
import numpy as np # 행렬연산을 쉽고 빠르게 할 수 있게 해주는 모듈

    return np.array(image)  # 어레이를 둘러줬다.

# 151. 이미지를 숫자로 변환하는 방법 (개와 고양이)  
개와 고양이 사진을 분류하는 인공신경망을 만들려면
개와 고양이 사진을 각각 2000장씩 내려받아서 숫자로 변환하는 작업을 해줘야합니다.  

예제1. 머신러닝 데이터 분석의 세계대회인 캐글에서 개와 고양이 사진을 내려받습니다.  

kaggle 검색에서 cat and dog  

CCU - 상업적으로 써도 무방  

예제2. 개사진 30장만 c드라이브 밑에 images2 라는 폴더에 넣으세요  

예제3. c드라이브 밑에 images2 라는 폴더에 있는 이미지 이름을 가져오는 함수를 image_load2 라는 함수로 생성하시오!

In [ ]:
import os
path = 'c:\\images2'
def image_load2(path):
    file_list=os.listdir(path)
    return file_list
print(image_load2(path))

예제4. 위의 개사진 이름에서 숫자만 출력하시오!  
예제5. file_name 리스트 안의 숫자를 정렬해서 출력되게 하시오!

In [ ]:
import os
path = 'c:\\images2'
def image_load2(path):
    file_list=os.listdir(path)
    file_name = []
    for i in file_list:
        a = re.sub('[^0-9]','',i)
        file_name.append(int(a))
    file_name.sort()
    return file_name
print(image_load2(path))

예제6. 아래와 같이 절대경로와 확장자가 붙어서 출력되게 하시오!
```
[c:\\images2\\dog1.jpg, ...]
```

In [ ]:
    file_name.sort()
    file_res = []       # 추가함
    for k in file_name:
        file_res.append(path+'\\dog.'+str(k)+'.jpg')
    return file_res

예제7. 위의 개사진 이미지들을 opencv와 numpy를 이용해서 숫자로 변환하고 numpy array로 반환되게 하시오.

In [ ]:
import numpy as np
import cv2
import os
path = 'c:\\images2'
def image_load2(path):
    file_list=os.listdir(path)
    file_name = []
    for i in file_list:
        a = re.sub('[^0-9]','',i)
        file_name.append(int(a))
    file_name.sort()
    file_res = []
    for k in file_name:
        file_res.append(path+'\\dog.'+str(k)+'.jpg')
    image = []
    for h in file_res:
        img = cv2.imread(h)
        image.append(img)
    return np.array(image)

print(image_load2(path))

문제480. (점심시간 문제) 지난번에 직접 스크롤링한 사진 20장을 c드라이브 밑 images3 폴더에 넣고 숫자로 변환하는 함수를 image_load3로 생성하시오.  

전 기수의 예: 스킨스쿠버 취미인 학생  
바다속에 자연보호를 위해서 비닐사진과 해파리 사진을 다운받아 비닐사진과 해파리 사진을 분류하는 인공신경망을 생성하는 포트폴리오를 생성  



In [ ]:
import numpy as np
import re
import cv2
import os
path = 'c:\\images3'
def image_load3(path):
    file_list = os.listdir(path)
    file_name = []
    for i in file_list:
        a = re.sub('[^0-9]','',i)
        file_name.append(int(a))
    file_name.sort()
    file_res = []
    for k in file_name:
        file_res.append(path+'\\'+str(k)+'_google.jpg')
    image = []
    for h in file_res:
        img = cv2.imread(h)
        image.append(img)
    return np.array(image,dtype=object))
print(image_load3(path))

# 152. 필수 알고리즘1 (합성곱 연산)  

알고리즘 문제를 풀어야 하는 이유?  

1. 지금까지 배운 파이썬 문법을 완성하는 단계 - 알고리즘 문제 해결  
2. 구글, 네이버, 카카오와 같이 큰 대기업으로 지원하고자 한다면 알고리즘 문제를 많이 풀어봐야 합니다.  
프로그래머스 사이트에 여러 알고리즘 문제들이 올라와 있음  
하루에 하나씩 꾸준히 풀면서 실력을 천천히 쌓아 올리면 됩니다.

* 합성곱 연산 알고리즘?  

딥러닝의 필수 알고리즘(퍼셉트론, 합성곱 연산 알고리즘)  
이미지의 형상을 무시하지 않고 이미지를 그대로 인공신경망이 학습할 수 있게 해준 수학 행렬 연산입니다.  
합성곱에서 원본 이미지는 학습해야할 데이터(사진) 이고 필터(filter)는 원본이미지에서 특징을 잡아내는데 사용되는 행렬입니다. 특징을 잡아서 feature map을 생성하여 원본 이미지의 형태를 이해하는 것을 합성곱 연산이라고 합니다.  

문제481. 아래의 두 행렬을 만들고 덧셈 연산을 하시오.
```
1 2 3     2 0 1
0 1 2  +  0 1 2
3 0 1     1 0 2
```

In [9]:
import numpy as np
a = [[1,2,3],[0,1,2],[3,0,1]]
b = [[2,0,1],[0,1,2],[1,0,2]]
a2 = np.array(a)
b2 = np.array(b)
print(a2)
print(b2)
a2+b2

[[1 2 3]
 [0 1 2]
 [3 0 1]]
[[2 0 1]
 [0 1 2]
 [1 0 2]]


array([[3, 2, 4],
       [0, 2, 4],
       [4, 0, 3]])

문제482. 아래의 두 행렬을 만들고 두 행렬의 곱을 구하시오.
```
a = [[1,2,3],[0,1,2],[3,0,1]]
b = [[2,0,1],[0,1,2],[1,0,2]]
```

In [12]:
np.dot(a2,b2)

array([[ 5,  2, 11],
       [ 2,  1,  6],
       [ 7,  0,  5]])

문제483. 위에서 출력된 결과의 요소들을 모두 다 더하시오.

In [13]:
result = np.dot(a2,b2)
print(result.sum()) # 행렬 안 원소들의 합을 출력

39


설명: numpy란 python 언어에서 기본적으로 지원하지 않는 배열(array) 혹은 행렬(matrix)의 계산을 쉽게 해주는 라이브러리입니다. 머신러닝에서 많이 사용하는 선형대수학에 관련된 수식들을 python에서 쉽게 프로그래밍 할 수 있게 해줍니다.  

문제484. 아래의 4x4 행렬을 만드시오.
```
1 2 3 0
0 1 2 3
3 0 1 2
2 3 0 1
```

In [15]:
a = [[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]]
np.array(a)

array([[1, 2, 3, 0],
       [0, 1, 2, 3],
       [3, 0, 1, 2],
       [2, 3, 0, 1]])

문제485. 아래의 4x4 행렬에서 빨간색으로 지정한 영역(좌상단3x3)의 숫자들만 출력하시오.

In [35]:
a = [[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]]
a2 = np.array(a)
print(a2[0:3,0:3]) # 행을 0 이상에서 3 미만까지, 열을 0 이상에서 3 미만까지

[[1 2 3]
 [0 1 2]
 [3 0 1]]


문제486. 아래의 4x4 행렬에서 빨간색으로 지정한 영역의 숫자들만 출력하시오.(우상단 3x3)

In [43]:
a = [[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]]
a2 = np.array(a)
print(a2[0:3,1:4])
        # 행 열

[[2 3 0]
 [1 2 3]
 [0 1 2]]


문제487. 아래의 4x4 행렬에서 빨간색으로 지정한 영역의 숫자들만 출력하시오(좌하단 3x3)

In [52]:
a = [[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]]
a2 = np.array(a)
print(a2[1:4,0:3])

[[0 1 2]
 [3 0 1]
 [2 3 0]]


문제488.아래의 4x4 행렬에서 우하단 3x3을 출력

In [53]:
a = [[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]]
a2 = np.array(a)
print(a2[1:4,1:4])

[[1 2 3]
 [0 1 2]
 [3 0 1]]


문제489. 아래의 4x4 행렬에서 위에서 빨간색으로 지정된 4개의 영역의 숫자들을(좌상 우상 좌하 우하) for loop 문을 이용해서 모두 출력하시오.

In [58]:
a = [[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]]
a2 = np.array(a)
for i in range(2):
    for k in range(2):
        print(a2[i:i+3,k:k+3])

[[1 2 3]
 [0 1 2]
 [3 0 1]]
[[2 3 0]
 [1 2 3]
 [0 1 2]]
[[0 1 2]
 [3 0 1]
 [2 3 0]]
[[1 2 3]
 [0 1 2]
 [3 0 1]]


문제490. 위에서 선택한 4개의 행렬(3x3)과 아래의 filter 행렬 (3x3)과의 원소의 곱을 출력하시오.
```
filter = [[2,3,4],[1,2,3],[2,0,1]]
```

In [63]:
a = [[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]]
a2 = np.array(a)
f = [[2,3,4],[1,2,3],[2,0,1]]
filter = np.array(f)

for i in range(2):
    for k in range(2):
        print(np.dot(a2[i:i+3,k:k+3],filter))



[[10  7 13]
 [ 5  2  5]
 [ 8  9 13]]
[[ 7 12 17]
 [10  7 13]
 [ 5  2  5]]
[[ 5  2  5]
 [ 8  9 13]
 [ 7 12 17]]
[[10  7 13]
 [ 5  2  5]
 [ 8  9 13]]


문제491. 원소의 합을 구하시오.

In [64]:
a = [[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]]
a2 = np.array(a)
f = [[2,3,4],[1,2,3],[2,0,1]]
filter = np.array(f)

for i in range(2):
    for k in range(2):
        print(np.dot(a2[i:i+3,k:k+3],filter).sum())

72
78
78
72


문제492. 위에서 출력된 4개의 숫자로 2x2 행렬을 만드시오
# 2x2행렬 만들기

In [67]:
a = [[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]]
a2 = np.array(a)
f = [[2,3,4],[1,2,3],[2,0,1]]
filter = np.array(f)
result = []
for i in range(2):
    for k in range(2):
        result.append(np.dot(a2[i:i+3,k:k+3],filter).sum())
result2 = np.array(result).reshape(2,2) # 2x2행렬로 변경
result2

array([[72, 78],
       [78, 72]])

설명: a2라는 원본이미지(개사진)에 filter(랜덤으로 생성한 이미지)를 가지고 원본 이미지를 스트라이드(양옆위아래로 스캔)하면서 특징을 잡아내어  

문제493. 아래의 원본 이미지 행렬(5x5) 행렬에서 필터행렬(4x4)로 스트라이딩해서 합성곱해서 특징(2x2)을 추출하시오.  
```
4x4 --> 3x3 --> 2x2
5x5 --> 4x4 --> 2x2
```

In [89]:
a = [ [2,3,1,4,7],[3,1,6,4,3],[2,1,5,3,1],[6,2,4,1,2],[7,3,1,2,3]]
a2 = np.array(a)
f = [ [3,1,4,1],[2,3,3,4],[5,1,2,1],[6,1,3,4]]
filter = np.array(f)
result=[]
for i in range(2):
    for k in range(2):
        result.append(np.sum(a2[i:i+4,k:k+4]*filter))
result2 = np.array(result).reshape(2,2)
print(result2)

[[138 121]
 [169 113]]


# 153. 필수 알고리즘2 (이진 탐색)
문제494. 아래의 리스트에서 숫자 3이 있는지 순차 탐색으로 구현하시오. 있으면 숫자 3이 있습니다. 라는 메세지가 출력되게 하시오.
```
a = [14,11,1,3,8]
```

In [93]:
a = [14,11,1,3,8]
for i in a:
    if 3 == i:
        print('숫자 3이 있습니다.')
        break

숫자 3이 있습니다.


설명: 순차탐색이란? 주어진 데이터를 처음부터 차례대로 비교하면서 찾는 방법

문제495. 위의 코드를 수정해서 숫자를 물어보게 하고 숫자를 입력하면 해당 숫자가 존재하는지 존재하지 않는지 출력되게 하시오.  

검색할 숫자를 입력하세요 ~ 3  
숫자 3은 있습니다.  
숫자 3은 없습니다.

In [106]:
a = [15,11,1,3,8]

b = input('검색할 숫자를 입력하세요 ~ ')
d = ''

if int(b[-1]) in [1,3,6,7,8,0]:
    d = '이'
else:
    d = '가'
    
for i in a:
    if int(b) == i:
        print(f'숫자 {b}{d} 있습니다.')
        break
else:
    print(f'숫자 {b}{d} 없습니다.')

검색할 숫자를 입력하세요 ~ 2
숫자 2가 없습니다.


이진탐색, 데이터가 순서대로 정렬되어 있으면 정 가운데부터 찾음 up down으로 비교.  

* 이진탐색 ? 정렬된 데이터를 좌우 둘로 나눠서 원하는 값의 탐색범위를 좁혀가며 찾는 방법  

문제496. 아래의 a 리스트에서 중앙값을 찾으시오!

In [109]:
a = [1,7,11,12,14,23,33,47,51,64,67,77,139,672,871]
import numpy as np
a_n = np.array(a)
print(np.median(a_n))

47.0


문제497. a 리스트에서 첫번째 숫자 부터 중앙값에 해당하는 숫자까지만 검색하시오 ~  

힌트: a.index(요소명)

In [117]:
a = [1,7,11,12,14,23,33,47,51,64,67,77,139,672,871]
import numpy as np
a_n = np.array(a)
a_m = np.median(a_n)
print(a[ :a.index(a_m)+1])

[1, 7, 11, 12, 14, 23, 33, 47]


문제498. 위의 a 리스트에서 문제497번에서 선택된 숫자들을 중앙값까지 포함해서 다 지우고 아래의 결과만 출력되게 하시오.

In [121]:
a = [1,7,11,12,14,23,33,47,51,64,67,77,139,672,871]
import numpy as np
a_n = np.array(a)
a_m = np.median(a_n)
del(a[ :a.index(a_m)+1]) # 지운다.
a

[51, 64, 67, 77, 139, 672, 871]

문제499. 위의 결과로 출력된 아래의 리스트에서 중앙값을 출력하시오.
```
[51, 64, 67, 77, 139, 672, 871]
```

In [129]:
a = [51, 64, 67, 77, 139, 672, 871]
a_n = np.array(a)
a_m = np.median(a_n)
a_m

77.0

문제500. 지금 위에서 출력한 중앙값 77이 내가 검색하고자 하는 67보다 크다면 아래의 결과 리스트만 출력되게 하시오.

In [130]:
if a_m > 67:
    del(a[:a.index(a_m)+1])
else:
    del(a[a.index(a_m)+1:])
a

[139, 672, 871]

문제501. 오늘의 마지막 문제) EBS에 나온 영상대로 이진탐색을 구현하시오. (필수 알고리즘 2번 문제)
```
a = [1,7,11,12,14,23,33,47,51,64,67,77,139,672,871]
a 리스트에서 검색할 숫자를 입력하세요 ~ 67
67은 이진탐색 3번만에 검색되었습니다.
a 리스트에서 검색할 숫자를 입력하세요 ~ 68
68
```

In [220]:
import numpy as np
a = [1,7,11,12,14,23,33,47,51,64,67,77,139,672,871]
b = (input('a 리스트에서 검색할 숫자를 입력하세요 ~ '))
cnt = 1
finish=0

if int(b[-1]) in [1,3,6,7,8,0]: # 은/는 불편해서 만듦
    d = '은'
else:
    d = '는'
b = int(b)

while True:
    a_m = round((len(a)-1)/2)

    if b == a[a_m]:
        print(f'{b}{d} 이진탐색 {cnt}번만에 검색되었습니다.')
        break
    elif b > a[a_m]:
        cnt +=1
        del(a[:a_m+1])
    else:
        cnt +=1
        del(a[a_m:])
    if len(a) == 0:
        print(f'{b}{d} 검색되지 않았습니다.')
        break

a 리스트에서 검색할 숫자를 입력하세요 ~ 1
1은 이진탐색 4번만에 검색되었습니다.
